twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        placeholder: 'mountains-5-transparent.png'
        placeholder_small: 'mountains-5-transparent-small.png'
    cache: false

when@test:
    twig:
        strict_variables: true
