twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        placeholder: 'mountains-5-desaturated.jpg'
        placeholder_small: 'mountains-5-desaturated-small.jpg'

when@test:
    twig:
        strict_variables: true
